package com.example.demo;

import java.util.ArrayList;
import java.util.Arrays;
import lombok.Data;

@Data
public class UserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Host
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private String user;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public UserKey(String host, String user) {
        this.host = host;
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public UserKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public static UserKey.Builder builder() {
        return new UserKey.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private UserKey obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder() {
            this.obj = new UserKey();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Host
         *
         * @param host the value for user.Host
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder host(String host) {
            obj.setHost(host);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.User
         *
         * @param user the value for user.User
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder user(String user) {
            obj.setUser(user);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public UserKey build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public enum Column {
        host("Host", "host", "CHAR", false),
        user("User", "user", "CHAR", false),
        selectPriv("Select_priv", "selectPriv", "CHAR", false),
        insertPriv("Insert_priv", "insertPriv", "CHAR", false),
        updatePriv("Update_priv", "updatePriv", "CHAR", false),
        deletePriv("Delete_priv", "deletePriv", "CHAR", false),
        createPriv("Create_priv", "createPriv", "CHAR", false),
        dropPriv("Drop_priv", "dropPriv", "CHAR", false),
        reloadPriv("Reload_priv", "reloadPriv", "CHAR", false),
        shutdownPriv("Shutdown_priv", "shutdownPriv", "CHAR", false),
        processPriv("Process_priv", "processPriv", "CHAR", false),
        filePriv("File_priv", "filePriv", "CHAR", false),
        grantPriv("Grant_priv", "grantPriv", "CHAR", false),
        referencesPriv("References_priv", "referencesPriv", "CHAR", false),
        indexPriv("Index_priv", "indexPriv", "CHAR", false),
        alterPriv("Alter_priv", "alterPriv", "CHAR", false),
        showDbPriv("Show_db_priv", "showDbPriv", "CHAR", false),
        superPriv("Super_priv", "superPriv", "CHAR", false),
        createTmpTablePriv("Create_tmp_table_priv", "createTmpTablePriv", "CHAR", false),
        lockTablesPriv("Lock_tables_priv", "lockTablesPriv", "CHAR", false),
        executePriv("Execute_priv", "executePriv", "CHAR", false),
        replSlavePriv("Repl_slave_priv", "replSlavePriv", "CHAR", false),
        replClientPriv("Repl_client_priv", "replClientPriv", "CHAR", false),
        createViewPriv("Create_view_priv", "createViewPriv", "CHAR", false),
        showViewPriv("Show_view_priv", "showViewPriv", "CHAR", false),
        createRoutinePriv("Create_routine_priv", "createRoutinePriv", "CHAR", false),
        alterRoutinePriv("Alter_routine_priv", "alterRoutinePriv", "CHAR", false),
        createUserPriv("Create_user_priv", "createUserPriv", "CHAR", false),
        eventPriv("Event_priv", "eventPriv", "CHAR", false),
        triggerPriv("Trigger_priv", "triggerPriv", "CHAR", false),
        createTablespacePriv("Create_tablespace_priv", "createTablespacePriv", "CHAR", false),
        sslType("ssl_type", "sslType", "CHAR", false),
        maxQuestions("max_questions", "maxQuestions", "INTEGER", false),
        maxUpdates("max_updates", "maxUpdates", "INTEGER", false),
        maxConnections("max_connections", "maxConnections", "INTEGER", false),
        maxUserConnections("max_user_connections", "maxUserConnections", "INTEGER", false),
        plugin("plugin", "plugin", "CHAR", false),
        passwordExpired("password_expired", "passwordExpired", "CHAR", false),
        passwordLastChanged("password_last_changed", "passwordLastChanged", "TIMESTAMP", false),
        passwordLifetime("password_lifetime", "passwordLifetime", "SMALLINT", false),
        accountLocked("account_locked", "accountLocked", "CHAR", false),
        sslCipher("ssl_cipher", "sslCipher", "LONGVARBINARY", false),
        x509Issuer("x509_issuer", "x509Issuer", "LONGVARBINARY", false),
        x509Subject("x509_subject", "x509Subject", "LONGVARBINARY", false),
        authenticationString("authentication_string", "authenticationString", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}