package com.example.demo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UserWithBLOBs extends User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_cipher
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private byte[] sslCipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_issuer
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private byte[] x509Issuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_subject
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private byte[] x509Subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.authentication_string
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    private String authenticationString;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public UserWithBLOBs(String host, String user, String selectPriv, String insertPriv, String updatePriv, String deletePriv, String createPriv, String dropPriv, String reloadPriv, String shutdownPriv, String processPriv, String filePriv, String grantPriv, String referencesPriv, String indexPriv, String alterPriv, String showDbPriv, String superPriv, String createTmpTablePriv, String lockTablesPriv, String executePriv, String replSlavePriv, String replClientPriv, String createViewPriv, String showViewPriv, String createRoutinePriv, String alterRoutinePriv, String createUserPriv, String eventPriv, String triggerPriv, String createTablespacePriv, String sslType, Integer maxQuestions, Integer maxUpdates, Integer maxConnections, Integer maxUserConnections, String plugin, String passwordExpired, Date passwordLastChanged, Short passwordLifetime, String accountLocked, byte[] sslCipher, byte[] x509Issuer, byte[] x509Subject, String authenticationString) {
        super(host, user, selectPriv, insertPriv, updatePriv, deletePriv, createPriv, dropPriv, reloadPriv, shutdownPriv, processPriv, filePriv, grantPriv, referencesPriv, indexPriv, alterPriv, showDbPriv, superPriv, createTmpTablePriv, lockTablesPriv, executePriv, replSlavePriv, replClientPriv, createViewPriv, showViewPriv, createRoutinePriv, alterRoutinePriv, createUserPriv, eventPriv, triggerPriv, createTablespacePriv, sslType, maxQuestions, maxUpdates, maxConnections, maxUserConnections, plugin, passwordExpired, passwordLastChanged, passwordLifetime, accountLocked);
        this.sslCipher = sslCipher;
        this.x509Issuer = x509Issuer;
        this.x509Subject = x509Subject;
        this.authenticationString = authenticationString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public UserWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public static UserWithBLOBs.Builder builder() {
        return new UserWithBLOBs.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public static class Builder extends User.Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private UserWithBLOBs obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder() {
            this.obj = new UserWithBLOBs();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Host
         *
         * @param host the value for user.Host
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder host(String host) {
            obj.setHost(host);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.User
         *
         * @param user the value for user.User
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder user(String user) {
            obj.setUser(user);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Select_priv
         *
         * @param selectPriv the value for user.Select_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder selectPriv(String selectPriv) {
            obj.setSelectPriv(selectPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Insert_priv
         *
         * @param insertPriv the value for user.Insert_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder insertPriv(String insertPriv) {
            obj.setInsertPriv(insertPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Update_priv
         *
         * @param updatePriv the value for user.Update_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder updatePriv(String updatePriv) {
            obj.setUpdatePriv(updatePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Delete_priv
         *
         * @param deletePriv the value for user.Delete_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder deletePriv(String deletePriv) {
            obj.setDeletePriv(deletePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_priv
         *
         * @param createPriv the value for user.Create_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createPriv(String createPriv) {
            obj.setCreatePriv(createPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Drop_priv
         *
         * @param dropPriv the value for user.Drop_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder dropPriv(String dropPriv) {
            obj.setDropPriv(dropPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Reload_priv
         *
         * @param reloadPriv the value for user.Reload_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder reloadPriv(String reloadPriv) {
            obj.setReloadPriv(reloadPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Shutdown_priv
         *
         * @param shutdownPriv the value for user.Shutdown_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder shutdownPriv(String shutdownPriv) {
            obj.setShutdownPriv(shutdownPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Process_priv
         *
         * @param processPriv the value for user.Process_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder processPriv(String processPriv) {
            obj.setProcessPriv(processPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.File_priv
         *
         * @param filePriv the value for user.File_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder filePriv(String filePriv) {
            obj.setFilePriv(filePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Grant_priv
         *
         * @param grantPriv the value for user.Grant_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder grantPriv(String grantPriv) {
            obj.setGrantPriv(grantPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.References_priv
         *
         * @param referencesPriv the value for user.References_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder referencesPriv(String referencesPriv) {
            obj.setReferencesPriv(referencesPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Index_priv
         *
         * @param indexPriv the value for user.Index_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder indexPriv(String indexPriv) {
            obj.setIndexPriv(indexPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Alter_priv
         *
         * @param alterPriv the value for user.Alter_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder alterPriv(String alterPriv) {
            obj.setAlterPriv(alterPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Show_db_priv
         *
         * @param showDbPriv the value for user.Show_db_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder showDbPriv(String showDbPriv) {
            obj.setShowDbPriv(showDbPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Super_priv
         *
         * @param superPriv the value for user.Super_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder superPriv(String superPriv) {
            obj.setSuperPriv(superPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_tmp_table_priv
         *
         * @param createTmpTablePriv the value for user.Create_tmp_table_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createTmpTablePriv(String createTmpTablePriv) {
            obj.setCreateTmpTablePriv(createTmpTablePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Lock_tables_priv
         *
         * @param lockTablesPriv the value for user.Lock_tables_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder lockTablesPriv(String lockTablesPriv) {
            obj.setLockTablesPriv(lockTablesPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Execute_priv
         *
         * @param executePriv the value for user.Execute_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder executePriv(String executePriv) {
            obj.setExecutePriv(executePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Repl_slave_priv
         *
         * @param replSlavePriv the value for user.Repl_slave_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder replSlavePriv(String replSlavePriv) {
            obj.setReplSlavePriv(replSlavePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Repl_client_priv
         *
         * @param replClientPriv the value for user.Repl_client_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder replClientPriv(String replClientPriv) {
            obj.setReplClientPriv(replClientPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_view_priv
         *
         * @param createViewPriv the value for user.Create_view_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createViewPriv(String createViewPriv) {
            obj.setCreateViewPriv(createViewPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Show_view_priv
         *
         * @param showViewPriv the value for user.Show_view_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder showViewPriv(String showViewPriv) {
            obj.setShowViewPriv(showViewPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_routine_priv
         *
         * @param createRoutinePriv the value for user.Create_routine_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createRoutinePriv(String createRoutinePriv) {
            obj.setCreateRoutinePriv(createRoutinePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Alter_routine_priv
         *
         * @param alterRoutinePriv the value for user.Alter_routine_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder alterRoutinePriv(String alterRoutinePriv) {
            obj.setAlterRoutinePriv(alterRoutinePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_user_priv
         *
         * @param createUserPriv the value for user.Create_user_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createUserPriv(String createUserPriv) {
            obj.setCreateUserPriv(createUserPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Event_priv
         *
         * @param eventPriv the value for user.Event_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder eventPriv(String eventPriv) {
            obj.setEventPriv(eventPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Trigger_priv
         *
         * @param triggerPriv the value for user.Trigger_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder triggerPriv(String triggerPriv) {
            obj.setTriggerPriv(triggerPriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.Create_tablespace_priv
         *
         * @param createTablespacePriv the value for user.Create_tablespace_priv
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder createTablespacePriv(String createTablespacePriv) {
            obj.setCreateTablespacePriv(createTablespacePriv);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.ssl_type
         *
         * @param sslType the value for user.ssl_type
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder sslType(String sslType) {
            obj.setSslType(sslType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.max_questions
         *
         * @param maxQuestions the value for user.max_questions
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder maxQuestions(Integer maxQuestions) {
            obj.setMaxQuestions(maxQuestions);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.max_updates
         *
         * @param maxUpdates the value for user.max_updates
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder maxUpdates(Integer maxUpdates) {
            obj.setMaxUpdates(maxUpdates);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.max_connections
         *
         * @param maxConnections the value for user.max_connections
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder maxConnections(Integer maxConnections) {
            obj.setMaxConnections(maxConnections);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.max_user_connections
         *
         * @param maxUserConnections the value for user.max_user_connections
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder maxUserConnections(Integer maxUserConnections) {
            obj.setMaxUserConnections(maxUserConnections);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.plugin
         *
         * @param plugin the value for user.plugin
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder plugin(String plugin) {
            obj.setPlugin(plugin);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.password_expired
         *
         * @param passwordExpired the value for user.password_expired
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder passwordExpired(String passwordExpired) {
            obj.setPasswordExpired(passwordExpired);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.password_last_changed
         *
         * @param passwordLastChanged the value for user.password_last_changed
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder passwordLastChanged(Date passwordLastChanged) {
            obj.setPasswordLastChanged(passwordLastChanged);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.password_lifetime
         *
         * @param passwordLifetime the value for user.password_lifetime
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder passwordLifetime(Short passwordLifetime) {
            obj.setPasswordLifetime(passwordLifetime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.account_locked
         *
         * @param accountLocked the value for user.account_locked
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder accountLocked(String accountLocked) {
            obj.setAccountLocked(accountLocked);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.ssl_cipher
         *
         * @param sslCipher the value for user.ssl_cipher
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder sslCipher(byte[] sslCipher) {
            obj.setSslCipher(sslCipher);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.x509_issuer
         *
         * @param x509Issuer the value for user.x509_issuer
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder x509Issuer(byte[] x509Issuer) {
            obj.setX509Issuer(x509Issuer);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.x509_subject
         *
         * @param x509Subject the value for user.x509_subject
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder x509Subject(byte[] x509Subject) {
            obj.setX509Subject(x509Subject);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column user.authentication_string
         *
         * @param authenticationString the value for user.authentication_string
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public Builder authenticationString(String authenticationString) {
            obj.setAuthenticationString(authenticationString);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public UserWithBLOBs build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table user
     *
     * @mbg.generated Sun Feb 06 01:24:55 CST 2022
     */
    public enum Column {
        host("Host", "host", "CHAR", false),
        user("User", "user", "CHAR", false),
        selectPriv("Select_priv", "selectPriv", "CHAR", false),
        insertPriv("Insert_priv", "insertPriv", "CHAR", false),
        updatePriv("Update_priv", "updatePriv", "CHAR", false),
        deletePriv("Delete_priv", "deletePriv", "CHAR", false),
        createPriv("Create_priv", "createPriv", "CHAR", false),
        dropPriv("Drop_priv", "dropPriv", "CHAR", false),
        reloadPriv("Reload_priv", "reloadPriv", "CHAR", false),
        shutdownPriv("Shutdown_priv", "shutdownPriv", "CHAR", false),
        processPriv("Process_priv", "processPriv", "CHAR", false),
        filePriv("File_priv", "filePriv", "CHAR", false),
        grantPriv("Grant_priv", "grantPriv", "CHAR", false),
        referencesPriv("References_priv", "referencesPriv", "CHAR", false),
        indexPriv("Index_priv", "indexPriv", "CHAR", false),
        alterPriv("Alter_priv", "alterPriv", "CHAR", false),
        showDbPriv("Show_db_priv", "showDbPriv", "CHAR", false),
        superPriv("Super_priv", "superPriv", "CHAR", false),
        createTmpTablePriv("Create_tmp_table_priv", "createTmpTablePriv", "CHAR", false),
        lockTablesPriv("Lock_tables_priv", "lockTablesPriv", "CHAR", false),
        executePriv("Execute_priv", "executePriv", "CHAR", false),
        replSlavePriv("Repl_slave_priv", "replSlavePriv", "CHAR", false),
        replClientPriv("Repl_client_priv", "replClientPriv", "CHAR", false),
        createViewPriv("Create_view_priv", "createViewPriv", "CHAR", false),
        showViewPriv("Show_view_priv", "showViewPriv", "CHAR", false),
        createRoutinePriv("Create_routine_priv", "createRoutinePriv", "CHAR", false),
        alterRoutinePriv("Alter_routine_priv", "alterRoutinePriv", "CHAR", false),
        createUserPriv("Create_user_priv", "createUserPriv", "CHAR", false),
        eventPriv("Event_priv", "eventPriv", "CHAR", false),
        triggerPriv("Trigger_priv", "triggerPriv", "CHAR", false),
        createTablespacePriv("Create_tablespace_priv", "createTablespacePriv", "CHAR", false),
        sslType("ssl_type", "sslType", "CHAR", false),
        maxQuestions("max_questions", "maxQuestions", "INTEGER", false),
        maxUpdates("max_updates", "maxUpdates", "INTEGER", false),
        maxConnections("max_connections", "maxConnections", "INTEGER", false),
        maxUserConnections("max_user_connections", "maxUserConnections", "INTEGER", false),
        plugin("plugin", "plugin", "CHAR", false),
        passwordExpired("password_expired", "passwordExpired", "CHAR", false),
        passwordLastChanged("password_last_changed", "passwordLastChanged", "TIMESTAMP", false),
        passwordLifetime("password_lifetime", "passwordLifetime", "SMALLINT", false),
        accountLocked("account_locked", "accountLocked", "CHAR", false),
        sslCipher("ssl_cipher", "sslCipher", "LONGVARBINARY", false),
        x509Issuer("x509_issuer", "x509Issuer", "LONGVARBINARY", false),
        x509Subject("x509_subject", "x509Subject", "LONGVARBINARY", false),
        authenticationString("authentication_string", "authenticationString", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user
         *
         * @mbg.generated Sun Feb 06 01:24:55 CST 2022
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}