package com.example.demo.MyBatis3Simple;

import example.model.Pkfields;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PkfieldsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:54 CST 2022
     */
    @Delete({
        "delete from PKFIELDS",
        "where ID2 = #{id2,jdbcType=INTEGER}",
          "and ID1 = #{id1,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("id2") Integer id2, @Param("id1") Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:54 CST 2022
     */
    @Insert({
        "insert into PKFIELDS (ID2, ID1, ",
        "FIRSTNAME, LASTNAME, ",
        "DATEFIELD, TIMEFIELD, ",
        "TIMESTAMPFIELD, DECIMAL30FIELD, ",
        "DECIMAL60FIELD, DECIMAL100FIELD, ",
        "DECIMAL155FIELD, wierd$Field, ",
        "\"birth date\", STRINGBOOLEAN)",
        "values (#{id2,jdbcType=INTEGER}, #{id1,jdbcType=INTEGER}, ",
        "#{firstname,jdbcType=VARCHAR}, #{lastname,jdbcType=VARCHAR}, ",
        "#{datefield,jdbcType=DATE}, #{timefield,jdbcType=TIME}, ",
        "#{timestampfield,jdbcType=TIMESTAMP}, #{decimal30field,jdbcType=DECIMAL}, ",
        "#{decimal60field,jdbcType=DECIMAL}, #{decimal100field,jdbcType=DECIMAL}, ",
        "#{decimal155field,jdbcType=DECIMAL}, #{wierdField,jdbcType=INTEGER}, ",
        "#{birthDate,jdbcType=DATE}, #{stringboolean,jdbcType=CHAR})"
    })
    int insert(Pkfields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:54 CST 2022
     */
    @Select({
        "select",
        "ID2, ID1, FIRSTNAME, LASTNAME, DATEFIELD, TIMEFIELD, TIMESTAMPFIELD, DECIMAL30FIELD, ",
        "DECIMAL60FIELD, DECIMAL100FIELD, DECIMAL155FIELD, wierd$Field, \"birth date\", ",
        "STRINGBOOLEAN",
        "from PKFIELDS",
        "where ID2 = #{id2,jdbcType=INTEGER}",
          "and ID1 = #{id1,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID2", property="id2", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ID1", property="id1", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATEFIELD", property="datefield", jdbcType=JdbcType.DATE),
        @Result(column="TIMEFIELD", property="timefield", jdbcType=JdbcType.TIME),
        @Result(column="TIMESTAMPFIELD", property="timestampfield", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DECIMAL30FIELD", property="decimal30field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL60FIELD", property="decimal60field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL100FIELD", property="decimal100field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL155FIELD", property="decimal155field", jdbcType=JdbcType.DECIMAL),
        @Result(column="wierd$Field", property="wierdField", jdbcType=JdbcType.INTEGER),
        @Result(column="birth date", property="birthDate", jdbcType=JdbcType.DATE),
        @Result(column="STRINGBOOLEAN", property="stringboolean", jdbcType=JdbcType.CHAR)
    })
    Pkfields selectByPrimaryKey(@Param("id2") Integer id2, @Param("id1") Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:54 CST 2022
     */
    @Select({
        "select",
        "ID2, ID1, FIRSTNAME, LASTNAME, DATEFIELD, TIMEFIELD, TIMESTAMPFIELD, DECIMAL30FIELD, ",
        "DECIMAL60FIELD, DECIMAL100FIELD, DECIMAL155FIELD, wierd$Field, \"birth date\", ",
        "STRINGBOOLEAN",
        "from PKFIELDS"
    })
    @Results({
        @Result(column="ID2", property="id2", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ID1", property="id1", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATEFIELD", property="datefield", jdbcType=JdbcType.DATE),
        @Result(column="TIMEFIELD", property="timefield", jdbcType=JdbcType.TIME),
        @Result(column="TIMESTAMPFIELD", property="timestampfield", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DECIMAL30FIELD", property="decimal30field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL60FIELD", property="decimal60field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL100FIELD", property="decimal100field", jdbcType=JdbcType.DECIMAL),
        @Result(column="DECIMAL155FIELD", property="decimal155field", jdbcType=JdbcType.DECIMAL),
        @Result(column="wierd$Field", property="wierdField", jdbcType=JdbcType.INTEGER),
        @Result(column="birth date", property="birthDate", jdbcType=JdbcType.DATE),
        @Result(column="STRINGBOOLEAN", property="stringboolean", jdbcType=JdbcType.CHAR)
    })
    List<Pkfields> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:54 CST 2022
     */
    @Update({
        "update PKFIELDS",
        "set FIRSTNAME = #{firstname,jdbcType=VARCHAR},",
          "LASTNAME = #{lastname,jdbcType=VARCHAR},",
          "DATEFIELD = #{datefield,jdbcType=DATE},",
          "TIMEFIELD = #{timefield,jdbcType=TIME},",
          "TIMESTAMPFIELD = #{timestampfield,jdbcType=TIMESTAMP},",
          "DECIMAL30FIELD = #{decimal30field,jdbcType=DECIMAL},",
          "DECIMAL60FIELD = #{decimal60field,jdbcType=DECIMAL},",
          "DECIMAL100FIELD = #{decimal100field,jdbcType=DECIMAL},",
          "DECIMAL155FIELD = #{decimal155field,jdbcType=DECIMAL},",
          "wierd$Field = #{wierdField,jdbcType=INTEGER},",
          "\"birth date\" = #{birthDate,jdbcType=DATE},",
          "STRINGBOOLEAN = #{stringboolean,jdbcType=CHAR}",
        "where ID2 = #{id2,jdbcType=INTEGER}",
          "and ID1 = #{id1,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Pkfields record);
}