package com.example.demo.MyBatis3;

import com.example.demo.MyBatis3.Pkfields;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PkfieldsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:22 CST 2022
     */
    int deleteByPrimaryKey(@Param("id2") Integer id2, @Param("id1") Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:22 CST 2022
     */
    int insert(Pkfields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:22 CST 2022
     */
    Pkfields selectByPrimaryKey(@Param("id2") Integer id2, @Param("id1") Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:22 CST 2022
     */
    List<Pkfields> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PKFIELDS
     *
     * @mbg.generated Sun Feb 06 00:26:22 CST 2022
     */
    int updateByPrimaryKey(Pkfields record);
}